#arithmetic operator use to perform a arithementic operations



'''
a = 12
b = 45
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b) # exponent is used to find cube , squar'''


# Find percentage using artimetic operator .....

'''hindi  = 56
english = 54
math = 84
science = 87
chemistry = 87
physics = 88
biology = 98

obtain = hindi+english+math+science+chemistry+physics+biology
total = 700

result = obtain/total*100

print(result)'''


# 2 - Assignment Operator is used to assign a value in between two Operands .


a = 10
b = 20

c = a=+b
print(c)
